---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install httpd
    yum: name=httpd state=present
  - name: start httpd
    service: name=httpd state=started
  - name: deploy html file
    copy: src=/target/addressbook.war dest=/var/www/html
    notify: restart httpd
  handlers:
  - name: restart httpd
    service: name=httpd state=restarted
